name: Reusable Workflow To Deploy MuleSoft Application

on:
  push:
    branches:
      - hotfix-v1.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17 


  deployprod:
    needs: build
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Deploy to prod
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
          -Danypoint.username="${{ secrets.USER }}" \
          -Danypoint.password="${{ secrets.PASS }}" \
          -Danypoint.businessGroup="${{ secrets.ANYPOINT_ORG_ID }}" \
          -Denv="${{ secrets.ENV }}" \
          -Dappname="${{ secrets.APP_NAME }}" \
          -Danypoint.platform.client_id="${{ secrets.ENV_CLIENT_ID }}" \
          -Danypoint.platform.client_secret="${{ secrets.ENV_CLIENT_SECRET }}" \
          -Dmule.env="${{ secrets.MULE_ENV }}" \
          -Dkey="${{ secrets.KEY }}"

